### ISSUE TITLE
Tag old release 1.51

### ISSUE THREAD

**Issue by akien-mga** [MCMic/jumpnbump#2]
It would be nice to add a git tag for 1.51 on e2bcb0a.

**Comment by MCMic** [comment]
Hum, did that and a push --tags, and a bunch of tags appeared from nowhere.
So, not sure where they come from, but you got tags for all old releases now.

**Comment by akien-mga** [comment]
Nice, they were probably already present in the git repo when you cloned it, but never pushed to GitHub.
